/**
 * PrintLayout — Shared branded print wrapper for all pages.
 *
 * Usage:
 *   const printRef = useRef(null);
 *   const handlePrint = useReactToPrint({ contentRef: printRef, documentTitle: '...' });
 *
 *   <PrintLayout ref={printRef} title="..." subtitle="..." meta={[{label,value}]} summary={[{label,value,color}]}>
 *     <table>...</table>   ← your content here
 *   </PrintLayout>
 *
 * Props:
 *   title     — Report heading
 *   subtitle  — Sub-heading
 *   meta      — Array<{ label, value }> shown as a tag row (period, filters, etc.)
 *   summary   — Array<{ label, value, color? }> shown as summary boxes above content
 *   children  — The table / content to print
 *   landscape — bool (default false) — sets @page to landscape in the injected CSS
 */
import React from 'react';
import logoImg from '../../assets/Gangadhara_logo.png';

const PrintLayout = React.forwardRef(function PrintLayout(
  { title, subtitle, meta = [], summary = [], children, landscape = false },
  ref
) {
  return (
    <div
      ref={ref}
      style={{
        fontFamily: "'Inter', Arial, sans-serif",
        padding: '28px 36px',
        color: '#0f172a',
        background: '#fff',
        minWidth: '600px',
      }}
    >
      {/* ── Header ── */}
      <div style={{
        display: 'flex', justifyContent: 'space-between', alignItems: 'flex-start',
        borderBottom: '2px solid #10b981', paddingBottom: '14px', marginBottom: '14px',
      }}>
        <div style={{ display: 'flex', alignItems: 'center', gap: '12px' }}>
          <img
            src={logoImg}
            alt="Gangadhara Nursery"
            style={{ width: '44px', height: '44px', borderRadius: '8px', objectFit: 'contain' }}
          />
          <div>
            <div style={{ fontSize: '18px', fontWeight: 800, color: '#059669', letterSpacing: '-0.3px' }}>
              Gangadhara Nursery
            </div>
            <div style={{ fontSize: '11.5px', fontWeight: 700, color: '#0f172a', marginTop: '1px' }}>{title}</div>
            {subtitle && <div style={{ fontSize: '9.5px', color: '#64748b', marginTop: '1px' }}>{subtitle}</div>}
          </div>
        </div>
        <div style={{ textAlign: 'right', fontSize: '10px', color: '#64748b' }}>
          <div style={{ fontWeight: 600, marginBottom: '2px' }}>Generated</div>
          <div>{new Date().toLocaleDateString('en-IN', { day: '2-digit', month: 'short', year: 'numeric' })}</div>
          <div style={{ marginTop: '2px' }}>{new Date().toLocaleTimeString('en-IN', { hour: '2-digit', minute: '2-digit' })}</div>
        </div>
      </div>

      {/* ── Meta filter tags ── */}
      {meta.length > 0 && (
        <div style={{
          display: 'flex', flexWrap: 'wrap', gap: '6px', marginBottom: '12px',
        }}>
          {meta.map((m, i) => (
            <span key={i} style={{
              background: '#f0fdf4', border: '1px solid #bbf7d0', borderRadius: '4px',
              padding: '3px 8px', fontSize: '9.5px', color: '#15803d', fontWeight: 600,
            }}>
              {m.label}: {m.value}
            </span>
          ))}
        </div>
      )}

      {/* ── Summary boxes ── */}
      {summary.length > 0 && (
        <div style={{ display: 'flex', gap: '10px', marginBottom: '14px' }}>
          {summary.map((s, i) => (
            <div key={i} style={{
              flex: 1, padding: '10px 14px',
              background: s.color === 'green' ? '#f0fdf4' : s.color === 'red' ? '#fef2f2' : '#f8fafc',
              border: `1px solid ${s.color === 'green' ? '#bbf7d0' : s.color === 'red' ? '#fecaca' : '#e2e8f0'}`,
              borderRadius: '8px',
            }}>
              <div style={{ fontSize: '8.5px', fontWeight: 700, textTransform: 'uppercase', letterSpacing: '0.7px', color: '#64748b' }}>
                {s.label}
              </div>
              <div style={{
                fontSize: '15px', fontWeight: 800, marginTop: '4px',
                color: s.color === 'green' ? '#059669' : s.color === 'red' ? '#dc2626' : '#0f172a',
                fontVariantNumeric: 'tabular-nums',
              }}>
                {s.value}
              </div>
              {s.sub && <div style={{ fontSize: '8.5px', color: '#94a3b8', marginTop: '2px' }}>{s.sub}</div>}
            </div>
          ))}
        </div>
      )}

      {/* ── Content ── */}
      {children}

      {/* ── Footer ── */}
      <div style={{
        marginTop: '20px', borderTop: '1px solid #e2e8f0', paddingTop: '8px',
        display: 'flex', justifyContent: 'space-between', fontSize: '8.5px', color: '#94a3b8',
      }}>
        <span>Gangadhara Nursery — Confidential Business Record</span>
        <span>Generated by Nursery Management System</span>
      </div>

      {/* Print page setup */}
      <style>{`
        @media print {
          @page { size: ${landscape ? 'A4 landscape' : 'A4 portrait'}; margin: 10mm; }
          body { -webkit-print-color-adjust: exact !important; print-color-adjust: exact !important; }
        }
      `}</style>
    </div>
  );
});

export default PrintLayout;

/* ── Shared print table styles (inline) ─────────────────── */
export const pTH = {
  padding: '7px 10px',
  borderBottom: '1.5px solid #e2e8f0',
  fontWeight: 700, textTransform: 'uppercase',
  fontSize: '8.5px', letterSpacing: '0.6px', color: '#64748b',
  background: '#f8fafc', whiteSpace: 'nowrap',
};

export const pTD = {
  padding: '6px 10px',
  borderBottom: '1px solid #f1f5f9',
  fontSize: '10.5px', verticalAlign: 'middle', whiteSpace: 'nowrap',
};

export const pTDRight = { ...pTD, textAlign: 'right', fontVariantNumeric: 'tabular-nums', fontWeight: 700 };

export const pAmt = (positive) => ({ color: positive ? '#059669' : '#dc2626', fontWeight: 800 });

export const pTable = {
  width: '100%', borderCollapse: 'collapse', fontSize: '10.5px',
};
